### ISSUE TITLE
Validation before submitting user request

### ISSUE THREAD

**Issue by shubham-asati** [gophers-prop/golang-appgen-ui#16]
**Describe the bug**
After clicking Download or Explore button, the UI should validate the appname with this regex  `^([a-zA-Z]{1,20})$`  then make the backend call . 

**To Reproduce**
1. go to http://golangapps.com/
2. Click on Download/Explore without filling appname
3. Check the network console .It calls backend server and the server respond with 400 bad request

**Expected behavior**
Download zip should be disabled in invalid appname

**Additional context**
the code for validation can be plugged into app.component.ts file for validation.

**We are new to angular so any easy/simple solution can work.**

**Comment by drishit96** [comment]
Hi, I would like to work on this issue. Please assign it to me.
Also, please add the `hacktoberfest` topic to this repository, otherwise my PR for this issue won't count for my hacktoberfest contribution.
For more info, refer: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by shubham-asati** [comment]
hi @drishit96  thank you for taking interest in this project. I have updated the topic for this repo.

**Comment by rajeshdeshpande02** [comment]
@drishit96 @shubham-asati  I have updated issue description. This validation should work for both functionality i.e. Download and Explore.
